### ISSUE TITLE
1.1.7 incorrect schedule validation & crashing

### ISSUE THREAD

**Issue by OSalama** [fivetran/terraform-provider-fivetran#243]
**Describe the bug**
We use manual schedules for our connectors, for which we do not specify any `sync_frequency`. Since 1.1.6/1.1.7 we are receiving the below error.
```
│ Error: Missing required argument
│ 
│   on modules/tenants/tenant-1.tf.json line 380, in resource.fivetran_connector_schedule.tenant_1_woocommerce:
│  380:       }
│ 
│ The argument "sync_frequency" is required, but no definition was found.
```

Further, after adding this parameter with some value, we receive another error:

```
╷
│ Warning: Failed to decode resource from state
│ 
│ Error decoding "module.tenants.fivetran_connector.tenant_1_woocommerce"
│ from prior state: missing expected {
╵
```

Reverting version to 1.1.5 fixed all issues.

**To Reproduce**
In .tf.json format:
```
"fivetran_connector_schedule": {
    "tenant_1_woocommerce": {
        "connector_id": "${fivetran_connector.tenant_1_woocommerce.id}",
        "lifecycle": {
          "ignore_changes": "all"
        },
        "pause_after_trial": false,
        "paused": false,
        "schedule_type": "manual"
    }
}
```

**Expected behavior**
Manual schedule should mean sync_frequency is not required. Alternatively, I'd be ok with setting a frequency of 0.
Would also expect such a breaking change to be an increment of minor version rather than patch version.

**Logs & Output**
```
│ Error: Missing required argument
│ 
│   on modules/tenants/tenant-1.tf.json line 380, in resource.fivetran_connector_schedule.tenant_1_woocommerce:
│  380:       }
│ 
│ The argument "sync_frequency" is required, but no definition was found.
```

**Plugin version:**
1.1.7

**Additional context**
N/A

**Comment by beevital** [comment]
@OSalama please check the latest 1.1.8 version, the issue should be fixed

**Comment by OSalama** [comment]
@beevital We only just got around to upgrading the provider version again, but it seems the issue is not fixed. We tested out 1.1.18, 1.1.26, and 1.2.0, but none of them are working.

Would you be able to reopen this issue please?
